import {lazy} from "react"
export const Inicio= lazy(()=> import(/* webpackChunkName: "home" */"./Inicio"))
// export const LandingIntriga = lazy(()=> import(/* webpackChunkName: "intriga" */"./LandingIntriga"))
export const LandingTerra = lazy(()=> import(/* webpackChunkName: "terra" */"./LandingTerra"))
export const LandingPiros = lazy(()=> import(/* webpackChunkName: "piros" */"./LandingPiros"))
export const Promotions= lazy(()=> import(/* webpackChunkName: "promotions" */"./Promotions"))
export const PromoPage = lazy(()=> import(/* webpackChunkName: "promo" */"./PromoPage"))
export const Multimedia = lazy(()=> import(/* webpackChunkName: "multimedia" */"./Multimedia"))
export const Nosotros= lazy(()=> import(/* webpackChunkName: "us" */"./Nosotros"))
export const PostVenta = lazy(()=> import(/* webpackChunkName: "postsale" */"./PostVenta"))
export const Fases = lazy(()=> import(/* webpackChunkName: "stages" */"./Fases"))
export const WorkingProgress = lazy(()=> import(/* webpackChunkName: "wirkinprogress" */"./WorkingProgress"))
export const SelectWorking = lazy(()=> import(/* webpackChunkName: "selectwkinprogress" */"./SelectWorking"))
export const ComplaintsBook = lazy(()=> import(/* webpackChunkName: "ComplaintsBook" */"./ComplaintsBook"))
export const Gracias = lazy(()=> import(/* webpackChunkName: "thankyou" */"./Gracias"))
export const GraciasPiros = lazy(()=> import(/* webpackChunkName: "thankyoupiros" */"./GraciasPiros"))
